### PR TITLE
fix: pushkin-prep should gracefully handle containers already existing and non-Pushkin templates

### LINKED ISSUE #365: pushkin prep hangs when docker containers are not built properly
outputs nothing even with --verbose flag on
Should figure out how to make it fail more gracefully + point people to debugging (check pushkin.yaml, run docker ps, manually build the failing docker container(s), etc.)

### LINKED ISSUE #367: pushkin prep fails for non-Pushkin site templates
Because it assumes the site template uses yalc and has the `/.yalc` file

### PR DESCRIPTION
**Pull request by cherriechang**
**1) Failing for existing container**
When running `pushkin-dev prep` with existing database containers from a previous run, the command would fail with a misleading "password authentication failed" error. This happened because the existing containers were using different credentials than the current pushkin.yaml config.

This commit implements Option 1 from the issue: automatic detection and cleanup of stale database containers.

Changes:
- Added `ensureCleanState()` function that checks for existing database containers before setup
- If containers exist, displays a warning and removes them cleanly
- Uses `docker ps -a` to detect both running and stopped containers
- Follows the same pattern as `killLocal()` using compose.stop() and compose.rm()
- Includes proper error handling to avoid failing the entire setup

Benefits:
- Makes `prep` command idempotent - safe to run multiple times
- Eliminates confusing password authentication errors
- Improves developer experience by avoiding manual cleanup steps
- No waiting through 10 failed connection attempts (~2+ minutes)

Fixes pushkin-dev prep fails cryptically when database containers already exist

**2) Failing for non-Pushkin site templates**

### CODE REVIEW

**Comment by becky-gilbert** [comment]
@cherriechang I've been hitting this issue while reviewing #373, so it would be nice to merge this ASAP! Is it ready for review?

**Comment by cherriechang** [comment]
> @cherriechang I've been hitting this issue while reviewing #373, so it would be nice to merge this ASAP! Is it ready for review?

I think so!

**Comment by jkhartshorne** [comment]
@becky-gilbert -- what's the status on this?

**Comment by becky-gilbert** [comment]
@jkhartshorne sorry, I've been focused on #383 and #376. This fix did work for me when I hit the issue but I'd like to take a closer look at the changes before approving. Will do ASAP!

File: packages/pushkin-cli/src/commands/setupdb/index.js [hunk 1]
```diff
@@ -336,18 +336,70 @@ export async function migrateTransactionsDB(coreDBs, verbose) {
...
+
+      const dockerPath = path.join(process.cwd(), "pushkin");
+      const dockerConfig = "docker-compose.dev.yml";
+
+      try {
+        // Remove containers and named volumes so new containers start with fresh credentials
+        await compose.down({
+          cwd: dockerPath,
+          config: dockerConfig,
+          commandOptions: ["--volumes"], // removes named volumes (e.g. test_transaction_db_volume)
```
Comment (becky-gilbert) [inline packages/pushkin-cli/src/commands/setupdb/index.js:366]: The -v flag on `compose.rm` only removes _anonymous_ volumes, so I switched from `compose.stop`/`compose.rm` to `compose.down` in order to also remove _named_ volumes: `pushkin_test_db_volume`, `pushkin_test_transaction_db_volume`. I ran into the same "password authentication failed" error with the original fix on this branch, which was because my test volumes survived the slate-cleaning process. The new container mounted the the old volume, which contained the PostgreSQL data directory with the old password.
The original fix did work for me before, but that was probably because either those named volumes hadn't been created yet or I'd cleared them.
Volume auth error before this change:
Image
After:
Image

File: packages/pushkin-cli/src/commands/setupdb/index.js [hunk 2]
```diff
@@ -336,18 +336,70 @@ export async function migrateTransactionsDB(coreDBs, verbose) {
...
+
   let dbPromise;
   if (verbose) console.log("Spooling up databases.");
   try {
     dbPromise = compose.upMany(["test_db", "test_transaction_db"], {
       cwd: path.join(process.cwd(), "pushkin"),
       config: "docker-compose.dev.yml",
     });
-  } catch {
+  } catch (e) {
```
Comment (becky-gilbert) [inline packages/pushkin-cli/src/commands/setupdb/index.js:402]: This bug wasn't introduced here, just cleaning it up anyway!

**Review by becky-gilbert — APPROVED** [review]
I happy this looks good and is working. @cherriechang do you want to test my changes before merging?

**Comment by becky-gilbert** [comment]
FYI @cherriechang, I ran into this same issue again by doing this: (1) ran `pushkin prep`, (2) deleted existing containers (but not volumes), (3) ran `pushkin prep` again. The check inside `ensureCleanSlate` is for existing _containers_, not volumes, so the compose down with --volumes never ran and my existing database volumes were not cleared. I think the easiest/safest solution is to remove the container check altogether and just always run compose down, even if there's nothing to clean up. I'm going to put my suggested fix in #373.

**Comment by becky-gilbert** [comment]
@cherriechang I changed my mind about the fix for this - new solution is [here](https://github.com/pushkin-consortium/pushkin/pull/373/changes/e3830d8131052c8274debc0bcc6d958644930a22). I decided to keep the container check and add a separate volumes check, and then gate compose down on either/both of those checks being true. I think this approach is a little more helpful for the user to understand what's happening and possibly debug if needed, especially with the verbose flag, since that will tell you exactly what containers/volumes are being cleared, if any.
